services:
  db-test:
    image: timescale/timescaledb:latest-pg15
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]
    ports:
      - "5433:5432" # Different host port to avoid conflict
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=tmg_db_test
